brick: ignore tap_burst error
outscale/packetgraph pull request #531
Opened 2020-03-25 19:17 UTC by outscale-toa

On some OS tap_brurt cannot write in /etc/net/tun file.
What make impossible to unlink vtep with another brick.

Signed-off-by: Thiery Ouattara <thiery.ouattara@outscale.com>

2020-03-26 09:21 UTC, outscale-mgo requested changes
also, thanks for the fix, but there is already a fix here:
https://github.com/outscale/packetgraph/pull/530 
if you could approve it, I could merge it

2020-03-26 09:21 UTC, outscale-mgo commented on src/brick.c
> +		if (!strcmp((*errp)->context.file, "src/tap.c") &&
I think you can ignore all error here, not only the one that would come  from a tap

2020-03-30 08:52 UTC, outscale-fne approved these changes
Not really understood the comment but it's working and clean.

2020-05-11 13:15 UTC, outscale-mgo requested changes

2020-05-11 13:15 UTC, outscale-mgo commented on src/brick.c
> -		return;
pg_error_free otherwise it would leak

2020-05-11 13:15 UTC, outscale-mgo commented on src/brick.c
> +	/* unlink brick. We will find the best way to ignore this error soon */
We will find the best way to ignore this error soon
...
yeah we all know that's a lie

2025-07-21 11:27 UTC, closed without merging